"""test migration

Revision ID: f615808360b6
Revises: 7e17b554456e
Create Date: 2025-07-24 01:18:47.495999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f615808360b6'
down_revision = '7e17b554456e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_integrations_user_provider'), 'integrations', type_='unique')
    op.drop_index(op.f('ix_users_normalized_email_unique_active'), table_name='users', sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_normalized_email_unique_active'), 'users', ['normalized_email'], unique=1, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_integrations_user_provider'), 'integrations', ['user_id', 'provider'])
    # ### end Alembic commands ###
