# Cloud Build configuration for Briefly services
# This file demonstrates how to build and deploy with GCP Secret Manager integration

steps:
  # Build frontend with build-time secrets
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '--build-arg'
      - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_CLERK_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'CLERK_SECRET_KEY=${_CLERK_SECRET_KEY}'
      - '--build-arg'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - '--build-arg'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-frontend:latest'
      - '.'

  # Build user management service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-user-service'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.user-service'
      - '--build-arg'
      - 'ENVIRONMENT=production'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-user-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-user-service:latest'
      - '.'

  # Build chat service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-chat-service'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.chat-service'
      - '--build-arg'
      - 'ENVIRONMENT=production'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-chat-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-chat-service:latest'
      - '.'

  # Build office service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-office-service'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.office-service'
      - '--build-arg'
      - 'ENVIRONMENT=production'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-office-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/briefly-office-service:latest'
      - '.'

  # Push all images
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-images'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/briefly-frontend']
    waitFor: ['build-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/briefly-user-service']
    waitFor: ['build-user-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/briefly-chat-service']
    waitFor: ['build-chat-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/briefly-office-service']
    waitFor: ['build-office-service']

  # Deploy to Cloud Run (optional)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-frontend'
    args:
      - 'run'
      - 'deploy'
      - 'briefly-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/briefly-frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'CLERK_SECRET_KEY=clerk-secret-key:latest'
      - '--update-secrets'
      - 'NEXTAUTH_SECRET=nextauth-secret:latest'
    waitFor: ['push-images']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-user-service'
    args:
      - 'run'
      - 'deploy'
      - 'briefly-user-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/briefly-user-service:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'briefly-backend@$PROJECT_ID.iam.gserviceaccount.com'
      - '--update-secrets'
      - 'DB_URL_USER=db-url-user:latest'
      - '--update-secrets'
      - 'CLERK_SECRET_KEY=clerk-secret-key:latest'
      - '--update-secrets'
      - 'REDIS_URL=redis-url:latest'
      - '--update-secrets'
      - 'TOKEN_ENCRYPTION_SALT=token-encryption-salt:latest'
    waitFor: ['push-images']

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _CLERK_PUBLISHABLE_KEY: '${_CLERK_PUBLISHABLE_KEY}'
  _CLERK_SECRET_KEY: '${_CLERK_SECRET_KEY}'
  _NEXTAUTH_URL: '${_NEXTAUTH_URL}'
  _NEXTAUTH_SECRET: '${_NEXTAUTH_SECRET}'

# Available secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/clerk-publishable-key/versions/latest
      env: '_CLERK_PUBLISHABLE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/clerk-secret-key/versions/latest
      env: '_CLERK_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/nextauth-url/versions/latest
      env: '_NEXTAUTH_URL'
    - versionName: projects/$PROJECT_ID/secrets/nextauth-secret/versions/latest
      env: '_NEXTAUTH_SECRET'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s' 