version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.11-bullseye"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000" # For Next.js frontend
      - "8000:8000" # For Python/FastAPI backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      # Frontend / Next.js specific vars
      - NEXTAUTH_URL=${NEXTAUTH_URL} # For NextAuth
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET} # For NextAuth
      - AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID} # For NextAuth Microsoft Provider
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET} # For NextAuth Microsoft Provider
      - AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID} # For NextAuth Microsoft Provider
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} # For Clerk
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY} # For Clerk
      # Add other necessary environment variables for the app service

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-briefly}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    restart: unless-stopped

volumes:
  postgres_data: 