"""add_user_drafts_table

Revision ID: a46de6cb2186
Revises: adc3b74054c1
Create Date: 2025-07-14 21:56:36.517801

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a46de6cb2186"
down_revision: Union[str, None] = "adc3b74054c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
