"""move email_message_id from package to tracking_event

Revision ID: 8867599ddb51
Revises: f0d1304ade40
Create Date: 2025-08-01 22:15:42.110777

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8867599ddb51"
down_revision: Union[str, Sequence[str], None] = "f0d1304ade40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove email_message_id from package table
    op.drop_column("package", "email_message_id")

    # Add email_message_id to trackingevent table
    op.add_column(
        "trackingevent",
        sa.Column(
            "email_message_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )

    # Create index and unique constraint for email_message_id
    op.create_index(
        op.f("ix_trackingevent_email_message_id"),
        "trackingevent",
        ["email_message_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_tracking_event_email", "trackingevent", ["email_message_id"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove email_message_id from trackingevent table
    op.drop_constraint("uq_tracking_event_email", "trackingevent", type_="unique")
    op.drop_index(op.f("ix_trackingevent_email_message_id"), table_name="trackingevent")
    op.drop_column("trackingevent", "email_message_id")

    # Add email_message_id back to package table
    op.add_column(
        "package",
        sa.Column(
            "email_message_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
