"""
Pydantic schemas package for User Management Service.

Exports all schema models for API request/response validation.
"""

from services.api.v1.user.health import (
    ConfigurationStatus,
    DatabaseStatus,
    DependencyStatus,
    PerformanceStatus,
    ReadinessChecks,
    ReadinessStatus,
)
from services.api.v1.user.integration import (
    IntegrationDisconnectRequest,
    IntegrationDisconnectResponse,
    IntegrationErrorResponse,
    IntegrationHealthResponse,
    IntegrationListResponse,
    IntegrationProviderInfo,
    IntegrationResponse,
    IntegrationScopeResponse,
    IntegrationStatsResponse,
    IntegrationSyncRequest,
    IntegrationSyncResponse,
    IntegrationUpdateRequest,
    InternalTokenRefreshRequest,
    InternalTokenRequest,
    InternalTokenResponse,
    InternalUserStatusResponse,
    OAuthCallbackRequest,
    OAuthCallbackResponse,
    OAuthStartRequest,
    OAuthStartResponse,
    ProviderListResponse,
    ScopeValidationRequest,
    ScopeValidationResponse,
    TokenRefreshRequest,
    TokenRefreshResponse,
)
from services.api.v1.user.preferences import (
    AIPreferencesSchema,
    IntegrationPreferencesSchema,
    NotificationPreferencesSchema,
    PreferencesExportResponse,
    PreferencesImportRequest,
    PreferencesResetRequest,
    PrivacyPreferencesSchema,
    UIPreferencesSchema,
    UserPreferencesResponse,
    UserPreferencesUpdate,
)
from services.api.v1.user.user import (
    UserBase,
    UserCreate,
    UserDeleteResponse,
    UserOnboardingUpdate,
    UserResponse,
    UserUpdate,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserDeleteResponse",
    "UserOnboardingUpdate",
    # Integration schemas
    "IntegrationResponse",
    "IntegrationListResponse",
    "IntegrationProviderInfo",
    "IntegrationScopeResponse",
    "IntegrationStatsResponse",
    "IntegrationHealthResponse",
    "IntegrationUpdateRequest",
    "IntegrationDisconnectRequest",
    "IntegrationDisconnectResponse",
    "IntegrationSyncRequest",
    "IntegrationSyncResponse",
    "IntegrationErrorResponse",
    "InternalTokenRequest",
    "InternalTokenResponse",
    "InternalTokenRefreshRequest",
    "InternalUserStatusResponse",
    "OAuthStartRequest",
    "OAuthStartResponse",
    "OAuthCallbackRequest",
    "OAuthCallbackResponse",
    "TokenRefreshRequest",
    "TokenRefreshResponse",
    "ProviderListResponse",
    "ScopeValidationRequest",
    "ScopeValidationResponse",
    # Preferences schemas
    "AIPreferencesSchema",
    "IntegrationPreferencesSchema",
    "NotificationPreferencesSchema",
    "PrivacyPreferencesSchema",
    "PreferencesExportResponse",
    "PreferencesImportRequest",
    "PreferencesResetRequest",
    "UserPreferencesResponse",
    "UserPreferencesUpdate",
    "UIPreferencesSchema",
    # Health schemas
    "DependencyStatus",
    "ConfigurationStatus",
    "DatabaseStatus",
    "PerformanceStatus",
    "ReadinessChecks",
    "ReadinessStatus",
]
