"""Office Service API Schemas and Models.

This package contains all the shared schemas and models for the office service,
enabling inter-service communication using consistent data structures.
"""

from services.api.v1.office.models import ApiCallStatus, Provider
from services.api.v1.office.schemas import (  # Email Models; Calendar Models; File Models; API Response Models; Availability Models; Calendar Event Response Models; Pagination Models; Error Models; Health Check Models; Contact Models; File Response Models; Type Aliases
    ApiError,
    ApiResponse,
    AvailabilityApiResponse,
    AvailabilityRequest,
    AvailabilityResponse,
    AvailableSlot,
    BaseApiResponse,
    Calendar,
    CalendarEvent,
    CalendarEventApiResponse,
    CalendarEventDetailResponse,
    CalendarEventList,
    CalendarEventListApiResponse,
    CalendarEventResponse,
    Contact,
    ContactCreateResponse,
    ContactDeleteResponse,
    ContactList,
    ContactPhone,
    ContactsListApiResponse,
    ContactUpdateResponse,
    Conversation,
    CreateCalendarEventRequest,
    CreateCalendarEventResponse,
    DriveFile,
    DriveFileList,
    DriveFileListApiResponse,
    EmailAddress,
    EmailDraftCreateRequest,
    EmailDraftResponse,
    EmailDraftResult,
    EmailDraftUpdateRequest,
    EmailFolder,
    EmailFolderList,
    EmailFolderListData,
    EmailMessage,
    EmailMessageList,
    EmailMessageListApiResponse,
    EmailMessageListData,
    EmailSendResult,
    EmailThread,
    EmailThreadList,
    EmailThreadListData,
    FileDetailResponse,
    FileListResponse,
    FileSearchResponse,
    FreeBusyInfo,
    HealthCheck,
    IntegrationHealthCheck,
    PaginatedResponse,
    SendEmailRequest,
    SendEmailResponse,
    TimeRange,
    TypedApiResponse,
)

__all__ = [
    # Core Models
    "Provider",
    "ApiCallStatus",
    # Email Models
    # Email Models
    "EmailAddress",
    "EmailMessage",
    "EmailThread",
    "Conversation",
    "EmailThreadListData",
    "EmailThreadList",
    "SendEmailRequest",
    "EmailSendResult",
    "SendEmailResponse",
    "EmailDraftCreateRequest",
    "EmailDraftUpdateRequest",
    "EmailDraftResult",
    "EmailDraftResponse",
    "EmailMessageListData",
    "EmailMessageList",
    "EmailFolder",
    "EmailFolderListData",
    "EmailFolderList",
    # Calendar Models
    "CalendarEvent",
    "Calendar",
    "CreateCalendarEventRequest",
    "CreateCalendarEventResponse",
    "CalendarEventList",
    "FreeBusyInfo",
    # File Models
    "DriveFile",
    "DriveFileList",
    # API Response Models
    "BaseApiResponse",
    "ApiResponse",
    "TypedApiResponse",
    # Availability Models
    "AvailabilityRequest",
    "AvailableSlot",
    "TimeRange",
    "AvailabilityResponse",
    # Calendar Event Response Models
    "CalendarEventResponse",
    "CalendarEventDetailResponse",
    # Pagination Models
    "PaginatedResponse",
    # Error Models
    "ApiError",
    # Health Check Models
    "HealthCheck",
    "IntegrationHealthCheck",
    # Contact Models
    "ContactPhone",
    "Contact",
    "ContactList",
    "ContactCreateResponse",
    "ContactUpdateResponse",
    "ContactDeleteResponse",
    # File Response Models
    "FileListResponse",
    "FileDetailResponse",
    "FileSearchResponse",
    # Type Aliases
    "AvailabilityApiResponse",
    "CalendarEventApiResponse",
    "CalendarEventListApiResponse",
    "EmailMessageListApiResponse",
    "DriveFileListApiResponse",
    "ContactsListApiResponse",
]
