name: Auto Fix

on:
  workflow_dispatch:
    inputs:
      pr_branch:
        description: 'Branch to fix'
        required: true
        type: string

jobs:
  python-auto-fix:
    name: Python Auto Fix
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.pr_branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with specific version if needed

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tox tox-gh-actions

      - name: Run formatter
        run: |
          chmod +x ./fix
          ./fix

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: auto-fix formatting" || echo "No changes to commit"
          git push origin HEAD:${{ inputs.pr_branch }}

